spring:
  cloud:
    nacos:
      discovery:
        namespace: ${NACOS_NAMESPACE:prd}
        group: ${NACOS_GROUP:SYNAPSE_PLATFORM_PRD}
      config:
        namespace: ${NACOS_NAMESPACE:prd}
        group: ${NACOS_GROUP:SYNAPSE_PLATFORM_PRD}

management:
  endpoint:
    health:
      show-details: never

synapse:
  oauth2:
    production: true
    key-id: ${SYNAPSE_OAUTH2_KEY_ID:}

logging:
  level:
    com.indigo.synapse: INFO
